### ISSUE TITLE
Add an option to report Android apps from Amazon (and other stores)

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#104]
At step "Where did you encounter the problem?" we should rename "Google Play App" to "Android App". Amazon is also using Android, but has their own store.

**Comment by vbagirov** [comment]
Simple renaming will not be enough. There are a number of reasons why, for example we can't use the Google Play algorithm to determine the number of installs (for priority purposes).

All in all, the idea is right, we need to be able to parse apps from Amazon (and maybe some other stores too), but it will take some work. Let's keep this issue open, but no milestone yet. It needs to be complemented.

**Comment by vbagirov** [comment]
This is not relevant anymore.
