### ISSUE TITLE
Change the page query when user enters data into the reports tool

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#107]
Basically, I need you to populate these fields when users enter information into the report:
https://github.com/AdguardTeam/ReportsWebApp#pre-filling-the-app-with-query-parameters

The goal is to construct a report URL that can be reused to create a new report so that people don't bother with choosing all the filters again.

I suppose that the easiest way to do it would be to use `replaceState` directly:
https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method

**Comment by vbagirov** [comment]
To clarify: the URL should be updated (supplemented with corresponding parameters) every time the user proceeds to the next step. 

Also, this URL should be used when the user clicks on the `Submit another issue` button (so that he/she doesn't have to enter all these settings again).

**Comment by vbagirov** [comment]
Important notice: the `url` parameter should not be included.

**Comment by vbagirov** [comment]
Done.
