### ISSUE TITLE
Handling the "paywall" websites

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#108]
There are some websites that we can't block the paywall on due to legal reasons. This is the current list of these websites:

 * bild.de
 * faz.net
 * tweaktown.com

(for more information on the matter see [AdGuard forum](https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/))

**What we should do:**

When user tries to enter a URL for one of these websites in the reporting tool, he should be shown a notice `Paywall on this website can't be blocked without legal repercussions. Please accept our apologies.` and the "Next" button should be unclickable.

The list of the websites may be modified in the future.

**Comment by danidoedel** [comment]
Well there could be other problems with these sites... not just anti adblock/paywall. Please take this into account.

**Comment by ameshkov** [comment]
Agreed with @danidoedel, I don't think we should handle these cases on the reports app side.

It should be handled by the filters devs, for instance we could keep the issues open and marked `wontfix`.

**Comment by BlazDT** [comment]
When user is selecting anti-adblock and url is one of those sites, show a message to the user and block the report.

**Comment by vbagirov** [comment]
Postponed until we have the recovery database, I guess.
