### ISSUE TITLE
Separate issues about same websites depending on the problem type

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#110]
Following problem types can be grouped:

 * `Missed ad`, `False positive` and `Anti-adblock script`
 * `Annoyances` and `Social`

Format for the issues' titles should be `example.org — Missed Ad` or `example.org — Annoyance`. The same holds true for Google Play apps.

**Comment by slavaleleka** [comment]
I suppose this is not relevant anymore
