### ISSUE TITLE
Demand two screenshots in case of False Positive — with and without AdGuard

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#111]
There should also be validation so that screenshots' URLs are diffirent.

It also makes sense to have a separate string for this case, as the description will be different compared to other problem types that require only one screenshot.

**Comment by vbagirov** [comment]
A phrase for the screenshot step description will be changed for now as a temporary measure.

**Comment by ameshkov** [comment]
@vbagirov let's prioritize this issue.

**Comment by vbagirov** [comment]
@IldarKamalov This should be done only for "False Positive" case: https://uploads.adguard.com/vbagirovmz7ry.png

@maximtop we need to add validation: if there are less than two screenshots uploaded, the "Next" button is not clickable.
