### ISSUE TITLE
Add uBlock Origin as a product

### ISSUE THREAD

**Issue by BooBerry** [AdguardTeam/ReportsWebApp#113]
I think you guys might need to add uBlock Origin as one of the products when prompted at the start of the reporting tool process. Reason being uBO uses AG's filters (and, if I recall correctly from the last time I checked, has the AG base filters enabled by default). There are a couple users on the AG forums, which uses uBO, reporting missed ads/anti-adblock/false positives/etc. so it doesn't make sense to exclude uBlock Origin from the product list since it supports AG's filters.

As such, you also probably have to rename the bolded **What AdGuard product do you use?** part to something else so it isn't AG exclusive.

I understand that automatic fill in required info will be impossible with uBO (along with the list of filters is different - uBO supports its own specific filters which *may* need to be accounted for in the tool if you're reporting for uBO).

**Comment by Alex-302** [comment]
You can select browser extension and add `uBO` as comment.

**Comment by ameshkov** [comment]
I guess we can simply add "Other" option and let people enter the name & version

**Comment by ameshkov** [comment]
Increased the feature request priority, there're some contributors with uBO, and we shouldn't ignore them.

**Comment by seanl-adg** [comment]
`pull-requests/62`

**Comment by vbagirov** [comment]
I'll rename the heading for this step from "What AdGuard product do you use?" to "What product do you use?" then.

**Comment by ameshkov** [comment]
@seanl-adg can I set product name directly in the URL?
