### ISSUE TITLE
Change the way we validate image URLs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#114]
Currently, you add an `img` element and check if it is loaded successfully. This is okay as a temporary solution, but it's time to improve it.

Instead of adding `img`, we should now send an XHR request to `window.image_upload_url` with method POST and a single parameter `url`.

This web service does some awesome things:
1. Validates the image
2. Handles gdrive/dropbox links
3. Uploads the image to imgur

**Carefully, pseudo-code below:**
```
addImagePreview(imageUrl); // Just to let user know that image validation is in progress
$.post(window.image_upload_url, {
    url: imageUrl
}).then(function(response) {
    if (response.url) {
        // Response is valid, use `response.url` from now on
        replaceImagePreview(response.url);
    } else {
        // Image is not valid, do something
    }
});
```

**Comment by seanl-adg** [comment]
`pull-requests/60`

**Comment by vbagirov** [comment]
@ameshkov guess we can close this, but paging you just in case.

**Comment by ameshkov** [comment]
Guys, I see that we've published that change.

Something is not okay with the validation though.

1. Imgur is blocked in Turkey
2. So when they pass a link to the image, we re-upload it to imgur and return the new link in response.
3. That new link is being validated again (that's unnecessary) and validation fails:

![2017-12-24_02-25-29](https://user-images.githubusercontent.com/5947035/34336520-e1901812-e968-11e7-98ea-95ca37ceeae4.png)

**Comment by ameshkov** [comment]
@seanl-adg to reproduce that issue, block imgur.com via hosts file

**Comment by ameshkov** [comment]
1. Remove the unnecessary check when you've got the image URL
2. Handle `img.onerror` and replace the `img.src` with a placeholder in case of a loading error: http://via.placeholder.com/300x200?text=Screenshot

**Comment by seanl-adg** [comment]
`pull-requests/73`

**Comment by ameshkov** [comment]
One more thing. 

To solve this issue once and for all, we can set up an imgur proxy, filed a new issue about that:
https://github.com/AdguardTeam/ReportsWebApp/issues/121

**Comment by sc0rp10** [comment]
@ameshkov https://reports-img.adguard.com/aKaOqIh.gif

**Comment by ameshkov** [comment]
@sc0rp10 no way!

**Comment by sc0rp10** [comment]
@ameshkov https://reports-img.adguard.com/CjYXag9.gif

**Comment by seanl-adg** [comment]
Tidied up some mischievous non-relevant comments :)
