### ISSUE TITLE
Improve step 5 (screenshot upload)

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ReportsWebApp#116]
unfortunately, way too many users are unable to provide a correct URL

it should also be possible to drag-and-drop\insert from clipboard etc.

---
if there are other suggestions about making it as convenient as possible for general user, please let me know

**Comment by altokarev** [comment]
I can confirm. We really need it.

Users are not able to add anything even they upload a screenshot to the cloud service. 

They are confused with a bunch of links which are given to them and can't understand how to manipulate next.

**Comment by vbagirov** [comment]
I suggest something like this: https://app.moqups.com/unsaved/080fbb1c/view/page/a3990f103

**Comment by ameshkov** [comment]
Broken link

**Comment by ameshkov** [comment]
Also, everything is already invented:
https://uploads.adguard.com/up04_ohnvq_Imgur_The_magic_of_the_Internet_.png

**Comment by vbagirov** [comment]
Fixed my link above. I also took an existing solution as a basis.

**Comment by vbagirov** [comment]
One more thing to consider: we can recommend some particular online services for capturing and modifying screenshots, e.g. https://www.printscreenshot.com/.

**Comment by altokarev** [comment]
No, we can't. People don't understand these services at all and what to do next.

We must implement own multi-upload box. That's the only way, I think.

**Comment by vbagirov** [comment]
>No, we can't. People don't understand these services at all and what to do next.
>We must implement own multi-upload box. That's the only way, I think.

I don't mean "instead", I mean "in addition to".

**Comment by bkrucarci** [comment]
It is now added, you may close this thread @ameshkov @vbagirov
