### ISSUE TITLE
Does not understand cyrillic domains

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/ReportsWebApp#118]
![default](https://user-images.githubusercontent.com/20907093/34126587-2ab4a35a-e44b-11e7-9f01-615fd16aed26.png)

**Comment by ameshkov** [comment]
@zovihuxij а если скопировать из адресной строки браузера?

Он его должен вот в такое превратить:
http://xn--80aacbuczbw9a6a.xn--p1ai/

Сожрет?

**Comment by zovihuxij** [comment]
> а если скопировать из адресной строки браузера?

При копирование из адресной строки url не преобразуется в такой вид, браузер firefox.

**Comment by vbagirov** [comment]
Done

**Comment by zovihuxij** [comment]
@vbagirov , по-прежнему не принимает
![image](https://user-images.githubusercontent.com/20907093/42078043-b3bcfee8-7b83-11e8-9447-595da95c998e.png)

**Comment by zovihuxij** [comment]
> "вписать урл руками на русском"

Как раз из адресной строки и копировал, в опере и мозиле не преобразуется в такой вид xn--80aacbuczbw9a6a.xn--p1ai

**Comment by vbagirov** [comment]
@zovihuxij на данный момент мы сделали так, что кириллица тоже воспринимается. 

@maximtop забыли сделать так, чтобы репорты сыпались в одну ишшу, например, для `куражбамбей.рф` и `xn--80aacbuczbw9a6a.xn--p1ai`. Переоткрою таск.

**Comment by Rakleed** [comment]
@vbagirov, @ameshkov на данный момент при попытке сообщить об URL с кириллицей опять ошибка появляется. Из-за этого невозможно отправить репорт о сайте.
