### ISSUE TITLE
Filters list empty

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#119]
https://github.com/AdguardTeam/AdguardFilters/issues/8621

According to issue above the reporting tool allows to continue if no filter is selected.

**Comment by vbagirov** [comment]
Honestly, I can't reproduce it. Are there more examples of such behavior?

**Comment by BlazDT** [comment]
That is the first one I have seen so far.

**Comment by vbagirov** [comment]
@BlazDT please post here if you come across more.

**Comment by vbagirov** [comment]
Still cant reproduce, please reopen if you can reproduce the issue consistently. Closing for now.
