### ISSUE TITLE
Set up an imgur proxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#121]
It'll help us solve this issue:
https://github.com/AdguardTeam/ReportsWebApp/issues/114#issuecomment-353849851

Basically, instead of supplying direct links to `i.imgur.com`, we can instead use proxy links to `reports-img.adguard.com`.

**Comment by vbagirov** [comment]
Implemented, confirmed to work by a guy from Turkey.

@ameshkov can it be closed?

**Comment by ameshkov** [comment]
Yep, thx

**Comment by BlazDT** [comment]
It seems not fully fixed.

https://forum.adguard.com/index.php?threads/cant-send-issue.27706/#post-163479

**Comment by vbagirov** [comment]
@BlazDT lets gather more data, looks like it works for the majority. Maybe the problem caused by a different reason for this user.

**Comment by ameshkov** [comment]
@vbagirov we've already figured what's the issue, it was AG blocking one important subrequest.

**Comment by bkrucarci** [comment]
@ameshkov @vbagirov 
https://forum.adguard.com/index.php?threads/cant-send-issue.27706/#post-163563
Please check the forum, it returned!!
