### ISSUE TITLE
block_third_party_auth parameter does not work

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/ReportsWebApp#123]
При отправке отчета через помощник, чекбокс "Блокировать заголовок Authorization" не выставляется, хотя в антитрекинге эта функция активирована.

![default](https://user-images.githubusercontent.com/20907093/34405968-7d4a5528-ebc7-11e7-9fb4-13d02e2b403f.png)

**Comment by ameshkov** [comment]
Полный адрес репорта можешь скопировать?

**Comment by zovihuxij** [comment]
https://reports.adguard.com/ru/new_issue.html?product_type=Win&product_version=6.2.437.2171&url=https%3A%2F%2Fyandex.ru%2F&user_agent=Mozilla%2F5.0%20(Windows%20NT%206.3%3B%20Win64%3B%20x64%3B%20rv%3A57.0)%20Gecko%2F20100101%20Firefox%2F57.0&filters=2.3.4.14.1.5&custom_filters=D%3A%5C%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8%5Cadguard_user_filter.txt&userscripts=https%3A%2F%2Fcdn.adguard.com%2Fpublic%2FUserscripts%2FBeta%2FAdguardAssistant%2F4.0%2Fassistant.user.js&win.wfp=true&stealth.enabled=true&stealth.hide_search_queries=false&stealth.DNT=true&stealth.x_client=true&stealth.disable_third_party_cache=true&stealth.webrtc=true&stealth.push=true&stealth.location=true&stealth.ip=43.236.224.0&stealth.flash=true&stealth.java=true&stealth.strip_url=true&block_third_party_auth=true

**Comment by ameshkov** [comment]
Нужно в винду переносить, не отправляется параметр.

**Comment by ameshkov** [comment]
@vozersky перенесешь?

**Comment by sc0rp10** [comment]
`block_third_party_auth` - это не про то, разве?

**Comment by ameshkov** [comment]
Ойвэй, поиск подвел

**Comment by zebrum** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2073](https://github.com/AdguardTeam/AdguardForWindows/issues/2073) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sc0rp10** [comment]
проблема не решена, к винде отношения не имеет

**Comment by ameshkov** [comment]
Damn, it is Win after all
