### ISSUE TITLE
Product label is 'undefined' when a selected product is 'Other'

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/ReportsWebApp#125]
Examples:
https://github.com/AdguardTeam/AdguardFilters/labels/undefined

**Comment by vbagirov** [comment]
Honestly, I don't know what "Other" even stands for. Can we just get rid of it altogether?

**Comment by ameshkov** [comment]
What do you mean? "Other" means an ad blocker that is not AdGuard

**Comment by vbagirov** [comment]
Do we really process complaints about other ad blockers not blocking something?

**Comment by ameshkov** [comment]
Yes, but with a lower priority

**Comment by slavaleleka** [comment]
@Martynuk could you please check it? I can't reproduce the issue now as far as I understand it

![slbdzd8ll4c62](https://user-images.githubusercontent.com/45171506/66674684-2ac9c480-ec6c-11e9-95f6-926c85da5d42.png)

**Comment by Martynuk** [comment]
Done
