### ISSUE TITLE
Issue removing the annoyance filter

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#126]
If I try to remove the annoyance filter nothing happens:

![grafik](https://user-images.githubusercontent.com/10995998/34906719-1b6ad234-f873-11e7-86dc-546dc6d468df.png)

And if I remove the english filter, the english fiter doesn't get removed, but the annoyance filter...

That's an example link:

https://reports.adguard.com/de/new_issue.html?product_type=Win&product_version=6.2.437.2171&url=https%3A%2F%2Fgithub.com%2FAdguardTeam%2FReportsWebApp%2Fissues&referrer=https%3A%2F%2Fgithub.com%2FAdguardTeam&user_agent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64%3B%20rv%3A57.0)%20Gecko%2F20100101%20Firefox%2F57.0&filters=2.3.4.6.14&userscripts=https%3A%2F%2Fcdn.adguard.com%2Fpublic%2FUserscripts%2FBeta%2FAdguardPopupBlocker%2F2.1%2Fpopupblocker.user.js%2Chttps%3A%2F%2Fcdn.adguard.com%2Fpublic%2FUserscripts%2FBeta%2FAdguardAssistant%2F4.0%2Fassistant.user.js&win.wfp=true&stealth.enabled=true&stealth.hide_search_queries=true&stealth.DNT=true&stealth.x_client=true&stealth.third_party_cookies=30&stealth.disable_third_party_cache=true&stealth.webrtc=true&stealth.push=false&stealth.location=true&stealth.flash=false&stealth.java=false&stealth.strip_url=false&block_third_party_auth=false

**Comment by vbagirov** [comment]
@danidoedel looks like the issue is gone, please let me know if we need to reopen it.
