### ISSUE TITLE
Unable to send report (Sorry, your report could not have been submitted)

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#127]
Unable to send a report:

![grafik](https://user-images.githubusercontent.com/10995998/34906817-2f11131e-f875-11e7-94ea-17c81bf3d0e2.png)

Used this link to report:
https://reports.adguard.com/en/new_issue.html?product_type=iOS&product_version=2.0.0&browser=Safari&ios.simplified=false&ios.systemwide=false&ios.DNS=None&filters=2.3.4.14.6.11.12

And tried to report this link:
https://www.washingtonpost.com/politics/trump-attacks-protections-for-immigrants-from-shithole-countries-in-oval-office-meeting/2018/01/11/bfc0725c-f711-11e7-91af-31ac729add94_story.html?hpid=hp_hp-top-table-main_trumpmeeting-445pm%3Ahomepage%2Fstory&utm_term=.636d4ee9a1f5

**Comment by sc0rp10** [comment]
got it, thanks!
fixed now: https://github.com/AdguardTeam/AdguardFilters/issues/9745
