### ISSUE TITLE
A deal with reporting tool

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/ReportsWebApp#128]
Hello everyone. I have some problems with reporting tool using AG asistant. For example, If I want to report any ad using AG asistant with Firefox Nightly, it redirects me to the default browser (Google Chrome) to report problem. But it'd be great if any user reported problem in the same browser, not in default. Have a good day. Thanks!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2099](https://github.com/AdguardTeam/AdguardForWindows/issues/2099) via [**ZenHub**](https://www.zenhub.com/)
