### ISSUE TITLE
Add these problem types

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/ReportsWebApp#130]
Could you add below problem types, please?

1) Adleftover
2) Malicous/Fake website
3) Popup

**Comment by vbagirov** [comment]
>Adleftover
>Popup

Both of these can go under "Missed Ad" without much of a problem

>Malicous/Fake website

This is not really abou AG filters, and doesn't even depend on the AG settings at all. You can report such websites on our [Forum](https://forum.adguard.com).

Maybe we'll come back to this at one point, but for now these problem types would be excessive.
