### ISSUE TITLE
Allow users to send reports w/o screenshots for some cases

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/ReportsWebApp#131]
As reported by user 983289,

"Step 5. “Please take a screenshot (or screenshots, if needed)”

It won’t let you past without a screenshot. Not all issues require a screenshot!!! An app timing out and giving no error does not need a screenshot.

I know you would prefer it, but you need ot allow us to get past this step without submitting a screenshot."

**Comment by ameshkov** [comment]
No way
