### ISSUE TITLE
Missed icons

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/ReportsWebApp#133]
Safari on iOS

reproducible only on iPhone X with developer beta though

<details>

![img_0109](https://user-images.githubusercontent.com/23637588/36099492-f25d72e4-1013-11e8-8335-357dbfd399eb.JPG)

</details>

**Comment by ameshkov** [comment]
@zebrum could it be blocked by AdGuard's social widgets filter?

**Comment by zebrum** [comment]
@ameshkov nope. 

if you reload the page all icons will appear.
