### ISSUE TITLE
Filter name is not listed at github

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#135]
@adreporter01 commented on [Mon Feb 19 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2121)

Hello,

I reported an issue using "reporting tool". My AG filters contain the following list:
English, Turkish, Russian, EasyPrivacy, Annoyances, Spyware, Social media and NoCoin filter list.

But, in my reported issue wan't listed "NoCoin filter list" at github. You can see this the following pic:

![screenshot_1053](https://user-images.githubusercontent.com/36031501/36391527-4dd37a68-15c0-11e8-81d9-4b556aae8e5f.png)

What is the reason of this?

**Comment by ameshkov** [comment]
We should sync known filters with https://github.com/AdguardTeam/FiltersRegistry

**Comment by BlazDT** [comment]
Icelandic
Finnish

When user selects those two filters on reports (have different names there), they get displayed as above in  issue report https://github.com/AdguardTeam/AdguardFilters/issues/11336#issuecomment-366887057
Probably others with long names too.
