### ISSUE TITLE
Add an explicit warning that all data entered by user will be made public

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/ReportsWebApp#137]
As reported by user #1655879,

"One thing that I wish I knew when I submitted an issue was that all of this
information entered will be made *public* on GitHub... could there be a
notice or warning for the user to keep that in mind? Esp. for sensitive
information."

**Comment by ameshkov** [comment]
This is important indeed

**Comment by planet0** [comment]
@ameshkov This was me. Was told about using the new tool via email support, and was expecting it to behave somewhat similarly between the user and AdGuard support, not automatically made public (on GitHub).

**Comment by vbagirov** [comment]
The phrase has been added, but we probably need to move it to the bottom (just above the buttons).
