### ISSUE TITLE
Ask if user uses the DNS feature when reporting

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/ReportsWebApp#138]
Noticed no question if I use the DNS feature in AdGuard for Android, which may or may not be useful to include since I enable DNS requests blocking and select AdGuard DNS, for example.

This info could be asked alongside other App configuration info like the filtering method, HTTPS filtering etc., in case the issue being reported could be related to using DNS blocking.

**Comment by vbagirov** [comment]
Makes sense to add it to step 4 (after the question about HTTPS filtering): 
"Do you use DNS filtering?"

We should also remember to take this into account in terms of integration with AG for Android.

**Comment by vbagirov** [comment]
Done, soon will be released.
