### ISSUE TITLE
Select problem type > Spyware

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/ReportsWebApp#139]
Hi,

Reporting tool does not include a header for AdGuard's Spyware Filter.Could you add a "Spyware" title to the reporting tool to report only counter and analytics scripts?

Thank you.

![spy](https://user-images.githubusercontent.com/34379403/37346347-229aca00-26e0-11e8-8223-6f6baaa5e143.png)

**Comment by vbagirov** [comment]
@PentagramTr for now you can report these as "Missed Ads", you can screenshot the devtools for example. But I aggree that there should be a separate problem type for that.

**Comment by ameshkov** [comment]
`Missed tracker` or smth like that

**Comment by vbagirov** [comment]
Further notes: screenshot should not be required, but the comment should be. Ideally we should display a notification in case of absent comment (like we do now when there's no screenshot etc.).
