### ISSUE TITLE
Rework step 6 (GitHub account prompt)

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#140]
Too often user's further collaboration is required to resolve the issue. We need to encourage more users to indicate their GitHub account. I suggest following changes:

- tick the "GitHUb" checkbox by default (https://uploads.adguard.com/vbagirovspojv.png)
- rephrase the question

Second part is on me.

**Comment by Alex-302** [comment]
Also add the comment, why this is important.

**Comment by vbagirov** [comment]
This will be covered by the "rephrase the question" part. I'll try to make it sound critical.

**Comment by vbagirov** [comment]
Done
