### ISSUE TITLE
The surplus "can" in the sentence on the website.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#145]
@aalpatkina

Well, I don't know where to report about your website.
Fix: "Existing customers can save up to 30% when you renew your license. You can also upgrade the license type or increase the number of devices."

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/BloLpZh.png)
</details><br/>

**Comment by vbagirov** [comment]
@lancelot-moon this is not the right repository to report such things. It is about the reporting tool (reports.adguard.com/new_issue.html).

If you need to report a typo on the website, you can use forum, our telegram channel or even translators telegram chat.
