### ISSUE TITLE
Please soon let Traditional Chinese Web Reporting Tool be online.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ReportsWebApp#152]
@lancelot-moon commented on [Sun Apr 22 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1838)

For Taiwanese users, now web reporting tool leads to English website in AG for Android v2.11.81.

Long~long time ago, Traditional Chinese Web Reporting Tool was very early 100% finished.
Please give Traditional Chinese Web Reporting Tool to Taiwanese users from next mirror version.

I also noted that you started to not anew update languages files in beta version, even release version.
I don't request every time for nightly / beta version.
At least, you should update languages files every time of release version.

Traditional Chinese for critical.xliff file of website is all finished.
The rate of progress for Traditional Chinese:
Total website: 81.3%
Web reporting tool: 100%

Please let Traditional Chinese website and web reporting tool be online.

Thanks a lot!

**Comment by vozersky** [comment]
@aalpatkina pls assist

**Comment by aalpatkina** [comment]
Traditional Chinese will be added to the Web Reporting Tool today and to the website in the near future.

**Comment by lancelot-moon** [comment]
@aalpatkina

Hi,
1. Thanks, I have seen that Traditional Chinese website and Web Reporting Tool be online.
I have a question.

Ex: I am a Taiwanese user.
Will it automatically detect the language of OS (Traditional Chinese) and then lead to Traditional Chinese Web Reporting Tool when I use Web Reporting Tool in AdGuard app?

Or do I need to manually choose language on website?

2. May you update Traditional Chinese website again?
I modified only a few translations.

B/R

**Comment by lancelot-moon** [comment]
Hi,

It seems that many content which were translated still show English.
Ex: the page of personal account

May you check it?

I'll gradually complete all of translations about website.

Thanks.

**Comment by lancelot-moon** [comment]
@aalpatkina 

May you update web reporting tool again?
You know some words have different meanings according to different situation.
After I actually saw my translations on web reporting tool, I modified only a few translations.
Thanks.

**Comment by lancelot-moon** [comment]
Today I check the website.
All translated content were finally online.
Thanks for the hard working!

May you update Web Reporting Tool again?

B/R

**Comment by vbagirov** [comment]
@lancelot-moon we will but not right now.

**Comment by vbagirov** [comment]
Done
