### ISSUE TITLE
The link to Web Reporting Tool on AdGuard official website.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#153]
Hi,

I think it's better to report issues via not only app but also AdGuard official website.

Please directly give the link to Web Reporting Tool on AdGuard official website, which is more convenient.

Thanks!

**Comment by Alex-302** [comment]
Already exists

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/ReportsWebApp/assets/8361299/8b923180-d500-4c73-89ac-e5a27dca6b50)


</details>
