### ISSUE TITLE
Unable to upload screenshots

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#158]
From time to time I'm unable to upload screenshots (stuck uploading) and I have to refresh the site a couple times. Same on mobile. That's really annoying...

E.g. here it didn't work (https://reports.adguard.com/en/new_issue.html?product_type=Win&product_version=6.3.1028.3331&url=http%3A%2F%2Fwww.chip.de%2F&user_agent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F68.0.3423.2%20Safari%2F537.36&filters=14.2.3.4.6.9&userscripts=https%3A%2F%2FAdguardTeam.github.io%2FAdguardAssistant%2Fassistant.user.js%2Chttps%3A%2F%2FAdguardTeam.github.io%2FPopupBlocker%2Fpopupblocker.user.js&win.wfp=true&stealth.enabled=true&stealth.hide_search_queries=true&stealth.DNT=true&stealth.x_client=true&stealth.third_party_cookies=30&stealth.disable_third_party_cache=true&stealth.webrtc=true&stealth.push=false&stealth.location=true&stealth.flash=false&stealth.java=false&stealth.strip_url=false&stealth.block_third_party_auth=false):

![image](https://user-images.githubusercontent.com/10995998/39873421-2e4800a8-546b-11e8-9254-c8948a8a4470.png)

Windows 10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3418.2 Safari/537.36

**Comment by zebrum** [comment]
https://uploads.adguard.com/up03_xjteg.png

**Comment by ameshkov** [comment]
Any screenshot or just this one? Something is not okay with the imgur API I guess

**Comment by sc0rp10** [comment]
yes, we have troubles with imgur api. i'll dive into this.

**Comment by vbagirov** [comment]
Done
