### ISSUE TITLE
Translate wrong in Turkish

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/ReportsWebApp#160]
![screenshot_101](https://user-images.githubusercontent.com/36031501/39968537-1c7017f8-56d7-11e8-90a8-b2c8a3c3c854.png)

Not "olduğu"  might be "olduğunu"

**Comment by vozersky** [comment]
@aalpatkina

**Comment by vozersky** [comment]
@ adreporter01 Hi! Thank you! 
And what about this phrase? 

> Ekran görüntüsünde sorunun ne olduğu açıkça belli olmuyorsa lütfen olabildiğince sorunu açıklamaya çalışın. Geliştiricilerin bilmesi gerektiğini düşündüğünüz bilgileri de yazabilirsi

Same?

**Comment by adreporter01** [comment]
@vozersky 

Ekran görüntüsünde sorunun ne olduğu açıkça belli olmuyorsa, lütfen olabildiğince sorunu açıklamaya çalışın. Geliştiricilerin bilmesi gerektiğini düşündüğünüz bilgileri de yazabilirsiniz.

This is correct.

**Comment by vozersky** [comment]
fixed in oneskyapp

**Comment by PentagramTr** [comment]
Wrong word | Correct word
---       | ---                         
`görüntüsünun` | `görüntüsünün`
`olcak` | `olacak`

Step 5
<details><summary>Screenshot:</summary>

![reports adguard com 2](https://user-images.githubusercontent.com/34379403/48665460-c33ce080-eabf-11e8-8e39-b40468ff2d29.png)



</details>
<br />

Step 7
<details><summary>Screenshot:</summary>

![reports adguard com 1](https://user-images.githubusercontent.com/34379403/48665462-cd5edf00-eabf-11e8-97db-fb6de2489e82.png)


</details>
<br />

Some missing letters.Please uptade.
@vozersky

**Comment by vozersky** [comment]
@vbagirov

**Comment by ameshkov** [comment]
@PentagramTr hi, have you checked https://adguard.oneskyapp.com? Is it already okay there?

**Comment by PentagramTr** [comment]
Still same.
<details><summary>Screenshot:</summary>

![adguard oneskyapp com](https://user-images.githubusercontent.com/34379403/48815820-d74b4100-ed50-11e8-81a3-e7d134a0ce8d.png)



</details>
<details><summary>Screenshot:</summary>

![adguard oneskyapp com 1](https://user-images.githubusercontent.com/34379403/48815801-c8fd2500-ed50-11e8-85f8-a1c3d729cce3.png)


</details>
<br />

There are too many translations here and I can't control them all.I found a few words not translated into the local language.

|  |  |
| --- | --- |
| Learn more | Daha fazla bilgi edinin |
| Annoyance (Pop-ups, notifications, etc.)  | Can sıkıcı öğe (Açılır pencereler,bildirimler,vb.) |
This was already reported | Bu zaten raporlandı

<details><summary>Screenshot:</summary>

![adguard oneskyapp com 2](https://user-images.githubusercontent.com/34379403/48815875-12e60b00-ed51-11e8-9f3d-d1fbb2141b54.png)


</details>
<details><summary>Screenshot:</summary>

![adguard oneskyapp com 3](https://user-images.githubusercontent.com/34379403/48815891-22655400-ed51-11e8-9f61-89244c98ef41.png)


</details>

**Comment by ameshkov** [comment]
@aalpatkina could you please assist and post a link to the proper oneskyapp project?
