### ISSUE TITLE
Add Firefox Mobile to the list of browsers

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#161]
Currently the user can only select Extension and FireFox. As the browser is also available on Android and not only on Windows and can help speed up to reproduce the issue, especially due to screen size the size can deliver the mobile version.

So please add in product type list the entry "AdGuard Browser extension (Mobile device)".

**Comment by ameshkov** [comment]
Renamed the task.

Also, do two more things:

1. Please change the sort order -- the most popular browsers should be on the top: Chrome, Safari, Firefox, Edge, Internet Explorer, Opera, and then other browsers
2. Also, rename Firefox Quantum -> Firefox

**Comment by Martynuk** [comment]
Done
