### ISSUE TITLE
Filters and filters groups need to be updated

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#163]
There were some major changes to them and I don't see them on the reports webapp.

https://filters.adtidy.org/windows/filters.json

**Comment by lancelot-moon** [comment]
Their translations also need to be updated.
Ex: English filter (英文過濾器) -> AdGuard Base filter (AdGuard 基本過濾器)

Hope that the option to report ads in iOS app via web reporting tool can be online together when updating translations for web reporting tool.
https://github.com/AdguardTeam/ReportsWebApp/issues/143#issuecomment-394169336

Thanks.

**Comment by vbagirov** [comment]
Looks like it's done now, at least for English,
