### ISSUE TITLE
IP based websites not reportable

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#172]
https://github.com/AdguardTeam/AdguardFilters/issues/19395

http://178.32.87.115/jetapi/?file=15121531044592

Next button can't be pressed on step 3/8 if an IP instead of a DNS is used.
Very likely those IP based websites have not visitors and we don't add rules for them to filter lists, but the user still should be able to report them.

**Comment by oleedd** [comment]
Just to make checking for digits and dots. It is an easy task.
`/(\d+\.?)+/`
or
`/[\d.]+/`

**Comment by Martynuk** [comment]
Done
