### ISSUE TITLE
Ctrl+V support for adding screenshots in creating an issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#175]
@oleedd commented on [Sat Aug 04 2018](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1061)

Please add this ability.

**Comment by oleedd** [comment]
It means pasting from clipboard.

**Comment by oleedd** [comment]
This way works:

document.addEventListener('paste', (e) => {
var items = (event.clipboardData  || event.originalEvent.clipboardData).items;
var image = items[0].getAsFile();
console.log(image);
})

**Comment by ameshkov** [comment]
Currently, it works only when the focus is on the input. We should capture it regardless of where the focus is at the moment, and if this is an image, we should upload it.

**Comment by Martynuk** [comment]
Done

**Comment by oleedd** [comment]
It doesn't work without the focus at the moment.

**Comment by slavaleleka** [comment]
@oleedd what exactly focus do you mean?

**Comment by oleedd** [comment]
()[https://reports-img.adguard.com/J7MqMQU.png]

**Comment by oleedd** [comment]
[](https://reports-img.adguard.com/J7MqMQU.png)

**Comment by oleedd** [comment]
[-](https://reports-img.adguard.com/J7MqMQU.png)

**Comment by oleedd** [comment]
![](https://reports-img.adguard.com/J7MqMQU.png)

**Comment by slavaleleka** [comment]
@oleedd if the focus is not only in the input but in the whole window — Ctrl+V paste the image at my end as it should. 
so could you please describe what's wrong on your side and how to reproduce that?

**Comment by oleedd** [comment]
Ctrl+V only works if to click the input (it gets green borders and the cursor appears there). If to click any another place of the page (the borders of the input become grey and no cursor there) - Ctrl+V stops to work.

**Comment by oleedd** [comment]
Ctrl+V only works if to click the input (it gets green borders and the text cursor appears there). If to click any another place of the page (the borders of the input become grey and no cursor there) - Ctrl+V stops to work.

**Comment by slavaleleka** [comment]
@oleedd could you please try in Private Mode without focusing on the input?

**Comment by oleedd** [comment]
The same.

**Comment by slavaleleka** [comment]
@oleedd provide your environment please: operating system and version, browser and version?

**Comment by oleedd** [comment]
Windows 7 + Chrome 65.

**Comment by oleedd** [comment]
To fix this issue, you can add this string (with `if`) here (in `bundle.js`):

![image](https://user-images.githubusercontent.com/36125949/85556319-66a48e80-b62f-11ea-87a9-67a041d8f79b.png)
In the above line, the focused element is assigned to `var t`.

**Comment by oleedd** [comment]
To fix this issue, you can add this string (with `if`) here (in `bundle.js`):

![image](https://user-images.githubusercontent.com/36125949/85558497-758c4080-b631-11ea-9b1e-1acde4c7b0b7.png)
In the above line, the focused element is assigned to `var t`.

**Comment by oleedd** [comment]
Why no reply?

**Comment by ameshkov** [comment]
@slavaleleka is on vacation, plz wait a little bit

**Comment by slavaleleka** [comment]
@oleedd 
I hope we'll fix this soon. thanks for reminding us!

**Comment by slavaleleka** [comment]
@oleedd 
could you please check it now? does it work as it's supposed to?

**Comment by oleedd** [comment]
Yes, but it just makes the focus on the input. It is a "dirty" workaround. My way is better.
The best way would be if to remove the check of  `event.target` and the input. But the code is too big, and I can't find it for now.

**Comment by oleedd** [comment]
What is about my solution?

**Comment by slavaleleka** [comment]
we are using React that's why your way is not acceptable

**Comment by oleedd** [comment]
I don't understand. I checked, and it works without any problems. Just check it in action.
