### ISSUE TITLE
Correctly display browser's name even when user-agent is included

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#176]
I use the latest Chrome v68.0.3440.84 on Windows.
Web reporting tool recognizes it as other.
Is it possible to fix it?

</details><br/><details><summary>Screenshot:</summary>

![image](https://i.imgur.com/RNJbjSj.png)
</details><br/>

Thanks.

**Comment by danidoedel** [comment]
Duplicate #78

**Comment by vbagirov** [comment]
In fact, let's use this issue as a task to find a better solution. I'll rename it.

**Comment by vbagirov** [comment]
@Martynuk we need to do something about it. Maybe show the user-agent string text box for all browsers and make it optional?

**Comment by lancelot-moon** [comment]
Is it due to stealth mode?
So failed to recognize it as Chrome.

**Comment by Martynuk** [comment]
Done
