### ISSUE TITLE
Rename English filter to Base filter

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ReportsWebApp#178]
Reporting tool detects Base filter as English.

1.
<img width="1038" alt="screen shot 2018-08-17 at 18 40 09" src="https://user-images.githubusercontent.com/17472907/44275351-2b73f000-a24d-11e8-8095-b7f7cdb2fd29.png">

2.
<img width="893" alt="screen shot 2018-08-17 at 18 40 48" src="https://user-images.githubusercontent.com/17472907/44275342-2747d280-a24d-11e8-90f7-3fcd40d59235.png">

**Comment by ameshkov** [comment]
Guys, we just need to start proper filters localization files:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/locales
