### ISSUE TITLE
Remove drop-down menu on step 3 for "Content Blocker" case

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#179]
As shown on this screenshot: https://uploads.adguard.com/vbagirovgiguc.png

**Comment by slavaleleka** [comment]
I suppose we should make Content Blocker list of supported browsers and show only 'Samsung Internet Browser' and 'Yandex Browser' in drop-down menu; even without opportunity to choose 'Other' and manually enter the browser name

**Comment by Martynuk** [comment]
Done
