### ISSUE TITLE
Please divide into 2 zones of screenshots when reporting incorrect blocking.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#185]
@ameshkov 

Well, I can make screenshots with/without AdGuard.
Since there is the only one zone of screenshots when reporting incorrect blocking, it's trouble to check which screenshot is with AdGuard and another is without AdGuard.
I'm also lazy to fill in which screenshot is with AdGuard and another is without AdGuard in the comment.

I wish 2 zones of screenshots when reporting incorrect blocking.
As the below, **"Without AdGuard:"** and **"With AdGuard enabled:"**.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/aePM8AF.png)
</details><br/>

Thanks.

**Comment by Chinaski1** [comment]
Done.
Now when sending a report about incorrect blocking, uploading screenshots is divided into 2 steps.
