### ISSUE TITLE
Sort filters list in report and divide it using groups like in new UI

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#187]
Now takes a lot of time to enable user's filters 
![image](https://user-images.githubusercontent.com/8361299/50361711-447b0d80-056d-11e9-9210-8d03aa93a653.png)

**Comment by ameshkov** [comment]
Something like this:

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.2.1
Browser: | Opera
Filters: | **Ad Blocking**<br>AdGuard Base,<br>AdGuard German,<br>AdGuard Russian<br><br>**Other**<br>Filter unblocking search ads and self-promotion,

**Comment by Martynuk** [comment]
Done
