### ISSUE TITLE
Update filters translations and handle strip tracking parameters extension option

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/ReportsWebApp#190]
As specified here https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1293
current filter name in the reporter is outdated
update it, please

Also, add strip tracking parameters options to the extension 
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1292

**Comment by slavaleleka** [comment]
first part's already done

second — strip tracking parameters are not really needed to be reported. so far there's [only one report with such parameters](https://github.com/AdguardTeam/AdguardFilters/search?q=utm_reader&type=Issues) which obviously was entered into wrong textfield
