### ISSUE TITLE
Better UI  for reporting an issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#193]
@F3000 commented on [Thu Mar 28 2019](https://github.com/AdguardTeam/AdguardForiOS/issues/933)

Hello , 

when I want to create a report I have difficult to see all the options from the drop down menu because the keyboard hides some of the entries

Would be nice when this drop down can be replaced by I iOS own drop down funtion. 

---

@F3000 commented on [Thu Mar 28 2019](https://github.com/AdguardTeam/AdguardForiOS/issues/933#issuecomment-477740748)

![ACFB842D-2971-43D7-8A6A-B74DC8AD12F1](https://user-images.githubusercontent.com/8161283/55187271-d613a000-5198-11e9-8788-07384f37f584.png)

**Comment by goodjohnjr** [comment]
Hello,

I would like to recommend improvements to the reporting form to include options in each section for people who need to report issues with Adguard DNS because most sections lack options for things related to Adguard DNS.

Thank you,
-John Jr

**Comment by ameshkov** [comment]
@goodjohnjr good idea, thank you! I've created a separate task for this: https://github.com/AdguardTeam/ReportsWebApp/issues/208

**Comment by goodjohnjr** [comment]
> 
> 
> @goodjohnjr good idea, thank you! I've created a separate task for this: #208

Hello @ameshkov,

You are welcome, and thank you.

-John Jr
