### ISSUE TITLE
Некорректное заполнение поля "браузер"

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/ReportsWebApp#196]
Почему при жалобе на сайт через Ассистент AdGuard в браузере Google Chrome на сайте https://reports.adguard.com/new_issue.html на 3 шаге в поле "браузер" заполняется "Другой" вместо Chrome? Не могли бы вы сделать так, чтобы заполнялся Chrome, пожалуйста?

У меня Google Chrome 74.0.3729.157, AdGuard 6.4.1814.4903, Помощник AdGaurd 4.3.10, [cкрин-рекординг](https://youtu.be/Xq5HEaWdA6E).

**Comment by Rakleed** [comment]
В AdGaurd 7.0.2693.6661 RELEASE с Помощник AdGaurd 4.3.13 теперь поле `Браузер` вообще остаётся пустым.

<details><summary>Screenshot:</summary>

![screenshot-reports-adguard-com-ru-new_issue-html-1559698828477](https://user-images.githubusercontent.com/19418601/58924318-191b6200-874c-11e9-80ee-91afc9d5612a.png)

</details>

**Comment by maximtop** [comment]
wait till AdGuard Windows client return correct querystring

**Comment by maximtop** [comment]
it may be necessary to add new querystring parameter `useragent`
also, do not forget to add in the readme

**Comment by Martynuk** [comment]
Done

**Comment by Rakleed** [comment]
@maximtop @Martynuk @ameshkov на последней версии AdGuard 7.3 всё ещё наблюдается данная проблема.

**Comment by maximtop** [comment]
@slavaleleka глянешь?

**Comment by slavaleleka** [comment]
@Rakleed в Адгарде для Виндовс поправят в одной из ближайших найтли, а в релизной версии будет уже в 7.4
