### ISSUE TITLE
Choose an approach to the client-side rendering.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#2]
You can either use a full-scale framework like ReactJS or AngularJS
You can use vanilla js + jquery + some simple template engine

As it is your first app, I suppose vanilla way would be more useful.

This task result should be:
1. A `new report` page rendered using the approach you've chose.
2. Make the page layout looking like a "step wizard".

    Here are some examples:
    http://bootsnipp.com/snippets/e3MBM
    http://mstratman.github.io/jQuery-Smart-Wizard/
    http://azmind.com/demo/bootzard-bootstrap-wizard-template/

Choose whatever steps you want, I'd just like to see which approach have you chosen.

**Comment by vbagirov** [comment]
I suppose it should be posted here:
here's a link to a template of the reporting tool 'step wizard' Many 'if-thens' there, I tried to describe everything relevant in the comments.

**Comment by ameshkov** [comment]
@vbagirov it'd be better to have a separate task.

**Comment by vbagirov** [comment]
@ameshkov ok #4

**Comment by ameshkov** [comment]
This one as well
