### ISSUE TITLE
It seems to confuse Web Annoyances Ultralist with (Obsolete) Czech List.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#204]
I don't enable (Obsolete) Czech List in AG for Windows.
(But I enabled `Web Annoyances Ultralist` before.)
https://github.com/AdguardTeam/AdguardFilters/issues/36926

From my issue, I found that it shows `(Obsolete) Czech List` in my filters' list.
I guess it confuses `Web Annoyances Ultralist` with `(Obsolete) Czech List`.

When I tried reporting an issue by AG for Android/Browser Extension, I got the same result.
The web reporting tool confuses `Web Annoyances Ultralist` with `(Obsolete) Czech List`.

**Comment by lancelot-moon** [comment]
May you also update the translations of web reporting tool afterwards?

Thanks.

**Comment by ameshkov** [comment]
It will be updated in due course when we update the webapp
