### ISSUE TITLE
Reported apps added to one issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#206]
https://github.com/AdguardTeam/AdguardFilters/issues/35190

For example:
https://apps.apple.com/CA/app/id725097967
https://apps.apple.com/us/app/sonos-controller/id293523031
https://apps.apple.com/ru/app/%D1%80%D0%B0%D0%B4%D0%B8%D0%BE-%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-radio/id1087161387

Better separate them by ID - `iOS app: id1087161387`

**Comment by Martynuk** [comment]
Done
