### ISSUE TITLE
Separate issues for Yandex domains

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#218]
At the moment `https://yandex.ru/` and `https://yandex.ru/news/` added in one issue.
For example https://github.com/AdguardTeam/AdguardFilters/issues/37603
Use `news.yandex.ru`(ua etc.) in issue name for `https://yandex.ru/news/`

Another yandex portal
https://yandex.ru/portal/tvstream?from=tv&win=381&stream_channel=100021
`portal.yandex.ru` does not exists, but can be used for issue name only.

How it's made for `https://yandex.ru/pogoda/` https://github.com/AdguardTeam/AdguardFilters/issues/24170

**Comment by Martynuk** [comment]
Done
