### ISSUE TITLE
Warn users about private info on screenshots and add instructions how to hide it

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#220]
At the moment a lot of users post screenshots with their emails and other info.
Notification should be conspicuous. And make shot description how to remove/blur sensitive info.
![image](https://user-images.githubusercontent.com/8361299/66210019-77882b00-e6c1-11e9-9973-309f1f646633.png)

**Comment by Martynuk** [comment]
Done
