### ISSUE TITLE
Please update the translations of web reporting tool.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#224]
There are new English phrases added into web reporting tool recently.
ex:
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/H4pAiyC.png)

![image](https://i.imgur.com/5JGe0QI.png)
</details><br/>

I had translated them on Crowdin.
I also fixed some translations on Crowdin, but they are still outmoded translations in web reporting tool.

It seems that you'll update the official website for the new licensing page.
Please also update the translations of web reporting tool together.
Thanks.

**Comment by Martynuk** [comment]
Done
