### ISSUE TITLE
When clicking AdGuard icon on web reporting tool page, it should lead to the homepage.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#229]
When clicking AdGuard icon on web reporting tool page, now it leads to:
https://reports.adguard.com/zh_tw/welcome.html
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KDtvhL7.png)
</details><br/>

Please fix the link to the homepage:
https://adguard.com/zh_tw/welcome.html

**Comment by ameshkov** [comment]
This is actually intended as this is the only way to get to the "reports.adguard.com" homepage

**Comment by lancelot-moon** [comment]
If I want to leave web reporting tool page and go to the welcome homepage, it's very inconvenient.
It'll lead to this.
https://reports.adguard.com/zh_tw/welcome.html
Actually, it's web security check page (check any website), not web reporting tool page.

Do you know there are 2 the same links on the page?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8XbEUyo.png)
</details><br/>

Giving 2 the same links doesn't make sense.

The AdGuard icon's link should be https://adguard.com/en/welcome.html.
