### ISSUE TITLE
May you add AdGuard for Safari in the products list of web reporting tool?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#230]
AdGuard for Safari is an individual product.
For distinguishing `AdGuard for Safari` from `AdGuard Browser Extension`, please add `AdGuard for Safari` in the products list of web reporting tool.

**Comment by lancelot-moon** [comment]
@slavaleleka 
@SoLenny 

Excuse me.
What's the information of app name and version which are exported to web reporting tool when reporting issues via AG for Safari?

AG for Browser Extension?

If so, AdGuard for Safari should export itself information after it becomes an individual product in the list of web reporting tool.
I don't know if you need to change program codes in AG for Safari.

**Comment by Martynuk** [comment]
Done
