### ISSUE TITLE
Use hCaptcha instead of ReCaptcha

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#239]
@ghost commented on [Sat Jun 27 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58125)

Предлагаю на сайте reports.adguard.com :
1. _**Добавить пункт "вредоносный/мошеннический сайт"**_
Зачем:
Очень не удобно отсылать заявки на блокировку вредоносных сайтов

2. **_Заменить ReCaptcha на hCaptcha_**
Зачем:
Я, например, не могу отправлять вам репорты через программу, так как у меня заблокированы все домены Гугла (я думаю, что я не один такой), а включать впн для этих целей не желаю.

Плюсов переезда с ReCaptcha на hCaptcha уйма:
* За нё не надо платить, в отличии от гугловской версии
* Надёжность. Сам Cloudflare на нё переехал.
Вот пруфы: https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/amp/
* Доступность. Пользователи, у которых заблокирован гугл (будь то работодателем или правительством) смогут ничего не нарушая отсылать вам репорты.
* hCaptcha платит вам.
Вот пруфы: https://www.hcaptcha.com/
* Конфиденциальность. hCapcha не собирает личные данные.

**Comment by Alex-302** [comment]
> * hCaptcha платит вам.
>   Вот пруфы: https://www.hcaptcha.com/
> * Конфиденциальность. hCapcha не собирает личные данные.

какие-то взаимоисключающие прараграфы.

**Comment by adblock520** [comment]
> > * hCaptcha платит вам.
> >   Вот пруфы: https://www.hcaptcha.com/
> > * Конфиденциальность. hCapcha не собирает личные данные.
> 
> какие-то взаимоисключающие прараграфы.

Не совсем. hCaptcha платит вам за то, что вы её используете. Подвох в том, что проходя её вы учите нейросеть распознавать что на картинке...

**Comment by ameshkov** [comment]
Да, hcaptcha хороший вариант, держали рекапчу только потому что альтернативы нормальной не было. Теперь есть - потестируем

**Comment by gitter10101** [comment]
> Да, hcaptcha хороший вариант, держали рекапчу только потому что альтернативы нормальной не было. Теперь есть - потестируем

Ок. Жду.

**Comment by Rakleed** [comment]
@ameshkov можно закрыть issue, так как эта возможность реализована.
