### ISSUE TITLE
Не работает штатный сервис issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#254]
@ghost commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875)

Здравствуйте!
Не могу отправить issue через штатный сервис.
Такое появляется без использования VPN:
![Screenshot_20201129-185619](https://user-images.githubusercontent.com/75215990/100548861-ecc89f00-3277-11eb-912b-c1e878c12ca5.jpg)
А такое с VPN:
![Screenshot_20201129-185024](https://user-images.githubusercontent.com/75215990/100548889-429d4700-3278-11eb-9e16-7ccf823b7c71.jpg)

Все фильтры отключал. Даже адгард отключал. Не помогает...

---

@ghost commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875#issuecomment-735427775)

Раньше VPN помогал отобразить капчу, а сейчас капча (причем данная проблема возникает **_ТОЛЬКО (!!!)_** с ReCAPTCHA) вообще не работает. Попробовал 3 VPN (Turbo VPN, Touch VPN, Betternet). Результата ноль. Такая проблема возникает на всех сайтах с рекапчей (именно рекапчей, остальные виды капч нормально работают)

---

@krystian3w commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875#issuecomment-735448586)

Maybe an overloaded site - it happens.

---

@krystian3w commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875#issuecomment-735448829)

If some software blocks for you loading Google captcha, you have to clean your computers from malware and check if the routers have been hacked on your home network.

---

@ghost commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875#issuecomment-735453625)

> If some software blocks for you loading Google captcha, you have to clean your computers from malware and check if the routers have been hacked on your home network.

Не, специально проверял на вирусы. Мало того, что у меня операционная система Linux, так еще и я проверял на разных сетях и на виртуалке. Может быть дело в том, что китайский фаервол снова химичит?

---

@ghost commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875#issuecomment-735454018)

И на мобильных гаджетах тоже не работает reCAPTCHA. А остальные работают нормально. Хотя на моих андроидах стоит антивирус + я сижу через мобильный интернет + все скачиваемые файлы я проверяю на VIRUSTOTAL. Наверное региональный блок...

---

@ghost commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68875#issuecomment-735454797)

Хотя при использовании Tor через мосты всё отлично работает...

Хивр

**Comment by ameshkov** [comment]
Господи давайте уже скорее на hCaptcha перейдем
