### ISSUE TITLE
Use quotes for GH usernames

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#256]
See the original issue:
https://github.com/AdguardTeam/ReportsWebApp/issues/255

This is a simple temporary solution that we can implement right away and mitigate the issue.

**Comment by Rakleed** [comment]
@ameshkov вы же на данный момент реализовали это, можно закрыть issue.

**Comment by rakleed** [comment]
@slavaleleka @ameshkov why did you remove the ability to specify a username, but not receive notifications in the new version?
