### ISSUE TITLE
"Submit" button is not actionable

### ISSUE THREAD

**Issue by AGreporter** [AdguardTeam/ReportsWebApp#263]
I'm trying to report missed ad, but for some unknown reason I cannot press "Submit" button. Checked for several sites - it's not specific for this one.
There's no error but button still greyed out:
![image](https://user-images.githubusercontent.com/74309036/107911437-a8db6100-6f6d-11eb-82ab-87fa66d3ba44.png)

**Comment by ameshkov** [comment]
Hm, looks as if captcha is missing.

Could it be that you have hcaptcha blocked?

**Comment by AGreporter** [comment]
Yep, it's kinda disappointing that hcaptcha has been choosed for report verification.

**Comment by ameshkov** [comment]
There're not too many alternatives to Google's recaptcha.

**Comment by slavaleleka** [comment]
@AGreporter 
remote access would be helpful because I can not reproduce the issue.
text me please if you can provide it: `v.leleka@adguard.com`

**Comment by AGreporter** [comment]
I already disabled hpatcha  filters and it works fine without it, thanks.

**Comment by slavaleleka** [comment]
you mean you've had some User rules for hCaptcha blocking?

**Comment by AGreporter** [comment]
Yep
