### ISSUE TITLE
Uploading screenshots does not work

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/ReportsWebApp#264]
Uploading screenshots neither by link nor by direct file upload does not work. There is just a placeholder with the caption "Screenshot", but after creating an issue on GitHub, you cannot see the screenshot.
![screenshot-reports-adguard-com-en-new_issue-html-1614857779689](https://user-images.githubusercontent.com/19418601/109958160-fd653700-7cf6-11eb-8f3a-75017c4bf08f.png)
Example: https://github.com/AdguardTeam/AdguardFilters/issues/76502

**Comment by slavaleleka** [comment]
unfortunately I can not reproduce the issue
are there any errors in browser console while screenshots uploading?

**Comment by rakleed** [comment]
@slavaleleka I also reproduce it somewhere in 10–20 % of cases. As I can reproduce, I will write the console log.

**Comment by rakleed** [comment]
@slavaleleka I still have never encountered this problem again, so it is no longer relevant.
