### ISSUE TITLE
Lower-casing URLs causes troubles

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#265]
See the details here:
https://github.com/AdguardTeam/AdguardFilters/issues/76930#issuecomment-792716018

**Comment by wout-codes** [comment]
@ameshkov @slavaleleka https://github.com/AdguardTeam/AdguardFilters/issues/77046

**Comment by wout-codes** [comment]
@ameshkov @slavaleleka https://github.com/AdguardTeam/AdguardFilters/issues/77223

**Comment by slavaleleka** [comment]
fixed

@wout-codes 
could you please try now?

**Comment by wout-codes** [comment]
I think it's fixed as seen in the test report. I am not the reporter of that reports so I do not know.
