### ISSUE TITLE
Prevent users from submitting reports by accident about websites that'll clearly never have problems, e.g. "adguard.com"

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/ReportsWebApp#278]
I came across https://github.com/AdguardTeam/AdguardFilters/issues/83709, and figured that the request in the above title could've slimmed down the AdGuard Filters issue report amount slightly.

Other apparent examples:
* https://github.com/AdguardTeam/AdguardFilters/issues?q=adguard.com+in%3Atitle+is%3Aclosed+ (33 results, including the one above)

**Comment by chirag127** [comment]
@DandelionSprout 

Adguard.com can have issues. It can clearly never have problems. Did you even tried to see the filtering log on adgaurd.com, it has Trackers, Ads, Annoyances. In the past, I have reported trackers like matomo (depreciated) as it was not present in Adguard tracking protection list .



<details><summary>Proof:</summary>
![image](https://user-images.githubusercontent.com/76880977/120486651-e0620200-c3d2-11eb-8626-8cdfa7a93632.png)
![image](https://user-images.githubusercontent.com/76880977/120486653-e0fa9880-c3d2-11eb-897f-86bc12348161.png)
![image](https://user-images.githubusercontent.com/76880977/120486656-e1932f00-c3d2-11eb-862a-0b60c4120140.png)
![image](https://user-images.githubusercontent.com/76880977/120486662-e22bc580-c3d2-11eb-80dd-0ea08b46d1ca.png)




</details><br/>


In addition, some rule or settings of a user may break the site .

**Comment by ameshkov** [comment]
Yep, excluding AG website would be strange, this is another way of communicating our own issues to us.
