### ISSUE TITLE
Dandelion Sprout's Annoyances List and Legitimate URL Shortener aren't showing up in the report form

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/ReportsWebApp#283]
While working on https://github.com/AdguardTeam/AdguardFilters/issues/91347, I realised that the 2 titular lists aren't showing up in the "Filters" selection list, let alone being chosen automatically by the report form. It would've been fairly nice to have that fixed.

It'll take me up to 24 hours to take a screenshot, since my phone really isn't in the mood to take a native screenshot of a popup menu, and I'm currently sitting on a train in eastern Sweden.

(Quicklink to the page with the filter selection, for the curious: `https://reports.adguard.com/en/new_issue.html?product_type=And&product_version=4.0%20nightly%2022%20(63)&filters=2.110.11.210.233.249.208.250&android_system_root=false&android_mode=VPN&android_method=High-quality&android_apps_filtering=true&https_filtering=true&dns_enabled=true&dns_servers=84.202.44.53&dns_filters_enabled=true&dns_filters=https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FSpecial%2520security%2520lists%2FDummyList.txt&dns_timeout=5000&dns_fallback_enabled=false&browsing_security_enabled=true&browsing_security_statistics_enabled=true&android_version=10&browser=Chrome&stealth_enabled=false&userscripts=https%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fadguard-extra%2F1.0%2Fadguard-extra.meta.js&url=https%3A%2F%2Fexample.org`)

**Comment by DandelionSprout** [comment]
A screenshot as promised (Half an hour late):
![image](https://user-images.githubusercontent.com/22780683/129878695-a91f337b-4b7c-42ab-889b-1f86070c79c9.png)

**Comment by slavaleleka** [comment]
thanks for the reports! 

it have been fixed, check it now

**Comment by DandelionSprout** [comment]
I can confirm that those lists are now present in the webform. That will make various AdGuard Filters reports a lot more informational for me to look through from now on.
