### ISSUE TITLE
UI translation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#29]
Here's what we need:

1. Find a way to translate the reporting tool UI ( @sc0rp10, thoughts? ). Maybe a json file with all the translations?
2. A script to upload/download translations to/from oneskyapp. For instance, here is a gulp task for downloading Assistant translations: https://github.com/AdguardTeam/AdguardAssistant/blob/master/tasks/download-localization.js

Please note, that the API key must not be in the repo.

**Comment by sc0rp10** [comment]
I wanna manage all translations in single place - into our backend and pass all clientside strings as key-value map as global variable.
I think we should use already implemented and tested 3rd party component - https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md

**Comment by ameshkov** [comment]
> key-value map as global variable.

So, basically, it will be a plain JSON object?

Then I guess @seanl-adg should compose the first version of that object and you'll take care of the oneskyapp integration.

**Comment by sc0rp10** [comment]
no, not just plain object, but full functional JS module with same interface as backend translator:
```js
import Translator from 'bazinga-translator';
// ...
alert(Translator.trans('hello.message'))</div>
```

**Comment by ameshkov** [comment]
@sc0rp10 

What format should @seanl-adg use to prepare the original English strings for you to load into bazinga?
