### ISSUE TITLE
Print license status to report

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#295]
Sometimes it is required to determine the reason of ads(usercsripts and apps filtering are available for premium only)

or print the reason why some modules are disabled(due to license, or disabled by user)

---

Also related to iOS (advanced blocking is disabled for free users and not all ads can be blocked, and we cannot find out the reason).

**Comment by Alex-302** [comment]
Also related https://github.com/AdguardTeam/ReportsWebApp/issues/311

**Comment by Alex-302** [comment]
*Ping*

**Comment by slavaleleka** [comment]
new parameter should be described in the README still

**Comment by slavaleleka** [comment]
I'll reopen the issue as no license status parameter is described in the readme yet
