### ISSUE TITLE
Choose a service allowing uploading & storing images

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#3]
Handling upload & storing & serving images on our side may be too complicated. I'd like to avoid coding it.

We have two options:

1. Find a self-hosted app, which can do it for us, which we can install & forget on our server: https://github.com/Kickball/awesome-selfhosted
2. Use a third-party service, for instance: https://api.imgur.com/

In the case of a third-party service, we don't mind paying for it.

This task should result in a "screenshots upload" step on the `new report` page.

**Comment by vbagirov** [comment]
@seanl-adg not relevant anymore?

**Comment by Martynuk** [comment]
@ameshkov can we close this issue? It seems to be implemented
