### ISSUE TITLE
Fill report with URL parameters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#30]
There should be a way to submit a link to a pre-filled report.

Here is what we need to be "pre-fillable":

1. Product type
2. Product version
3. Stealth mode settings
4. Browser and version
5. Page URL or app's package name
6. Enabled filters

**Comment by seanl-adg** [comment]
Currently there is a small problem with page validation and pre-filling problem url field.

**Comment by ameshkov** [comment]
> Currently there is a small problem with page validation and pre-filling problem url field.

What kind of a problem?

**Comment by seanl-adg** [comment]
It's done
