### ISSUE TITLE
Mask AdGuard cloud DNS and NextDNS id

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#300]
https://github.com/AdguardTeam/AdguardFilters/issues/118020
For example `https://4e499c73.d.adguard-dns.com/dns-query` => `https://********.d.adguard-dns.com/dns-query`
https://github.com/AdguardTeam/AdguardFilters/issues/122457
`https://dns.nextdns.io/fb*1fd` => `https://dns.nextdns.io/******`

Or remove an ID when creating report(in this case issues must be opened in related repositories)

**Comment by Alex-302** [comment]
*Ping*
Now we have more than 150 reports with AdGuard private DNS, not including another services.

**Comment by slavaleleka** [comment]
done
