### ISSUE TITLE
Suggestion: Adding Advanced Protection Information for reporting with AG for iOS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/ReportsWebApp#311]
Advanced Protection brings more compatibility and therefore I think it could help with fixing issues.

**Comment by sugarfreesweetener** [comment]
@Alex-302 @AdamWr Since you are maintainers of AdGuard Filters, any thoughts? Should/could I move this issue somewhere else? Has anyone been notified of it?

**Comment by AdamWr** [comment]
I guess that this the correct place for this report/suggestion and we just have to wait as (if) it will be implemented.
