### ISSUE TITLE
We should also ask about third-party add-ons

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#33]
Here is an example of an issue caused by third-party add-ons:
https://github.com/AdguardTeam/AdguardForWindows/issues/1841

Besides regular questions, we should also ask people to add information about add-ons installed.

**Comment by Alex-302** [comment]
What about antivirus software? For example, Kaspersky Internet Security has own ad blocking module.

**Comment by ameshkov** [comment]
@Alex-302 as I recall, it is a browser extension as well

**Comment by Alex-302** [comment]
@ameshkov no, it is a part of the application

![image](http://imagizer.imageshack.com/img924/7504/HpWw9g.png)

https://support.kaspersky.ru/12156#block2

**Comment by ameshkov** [comment]
Technically, it is achieved through their extension

**Comment by Alex-302** [comment]
Their extension is removed from my browser. Ad blocking still works.

**Comment by ameshkov** [comment]
Ok, convinced me:)

**Comment by seanl-adg** [comment]
How about asking users instead to try disabling other browser extensions and anti-virus software (or whatever that might interfere with Adguard)? It is not a filter issue when an issue disappears after disabling certain addons, and such issue would rather not be posted on AdguardFilters repo.

**Comment by TPS** [comment]
> How about asking users instead to try disabling other browser extensions and anti-virus software (or whatever that might interfere with Adguard)? It is not a filter issue when an issue disappears after disabling certain addons, and such issues should rather not be posted on AdguardFilters repo.

@seanl-adg Posting as a medium-level technical user, it's actually quite hard for any user below this level (most of your base, I think) to actually _know_ this, but, more importantly, also for us to _want_ to try this.

Here's the thinking (indulge me, I _know_ it's faulty!) for such users:
"AdGuard is _just_ an ad-blocker.  Side-loading _(a new scary thing for many)_ it was already worrisome for me.  Why should I {disable | uninstall} my favorite {security app | cat video player | Pokemon clone | _take your pick_} that I downloaded from {Play store | friend | somewhere else I trust} just to make AdGuard do its job?!  It should 'just work'!  Boo!  I'll uninstall _it_ & leave a crummy _(albeit ignorant & irrational)_ review many, _many_ places!"

 …  Which, of course, is more effort than _actually_ doing the debug steps, but there you go.  The only grain of truth to the whole thing is that AG _is_ an adjunct to 1s online life & "just work"ing (set & forget) is _critical_ to its function.

**Comment by seanl-adg** [comment]
Done in https://github.com/AdguardTeam/ReportsWebApp/pull/39
