### ISSUE TITLE
Wrap GitHub user name in the comment tag

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#343]
### Details

Users do not read, and enter random names or even one symbol

<details>
<summary>Example</summary>

![image](https://github.com/AdguardTeam/ReportsWebApp/assets/8361299/b8e46601-5ed7-4313-a555-5a636993c71b)

</details>

More examples here (many reports in one issue): https://github.com/AdguardTeam/AdguardFilters/issues/162262

### Proposed solution: 

convert @username to 
```
`@username`
```
to avoid summoning of foreign user.

**Comment by DandelionSprout** [comment]
Appears to have been fixed a month or two ago, from what I can personally determine.

**Comment by Alex-302** [comment]
Yep.
