### ISSUE TITLE
All screenshots are marked NSFW

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/ReportsWebApp#349]
All screenshots began to be marked as NSFW, although this problem did not exist a week ago. Please fix it.

**Comment by DandelionSprout** [comment]
I was honestly convinced it was intentional on Team AdGuard's part to *really* defend themselves against pornographic images on GitHub's servers, but it does seem fully believable that it could be an unintentional bug indeed.

**Comment by Chinaski1** [comment]
Fixed
