### ISSUE TITLE
Issue reporting tool adds the NSFW tag even if 'no' is selected

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/ReportsWebApp#357]
See below screenshots where 'no' was selected for the NSFW section, yet still added the NSFW tag.
This has happened with a few submissions now.

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/149243371/19d4fb1f-1708-42f0-8b6b-8446af804d01)

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/149243371/23073f38-4609-456b-9f63-5f1c30df6b20)

**Comment by Chinaski1** [comment]
Fixed
