### ISSUE TITLE
Apply Norwegian translated strings to the Reports web form

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/ReportsWebApp#363]
Currently, very few strings in the web form show up in the form, as it turned out that strings were required to be validated in order to show up, and it appears I've lost (or never had) validation rights at https://crowdin.com/editor/adguard-websites/17520/en-no?view=comfortable&filter=basic&value=5.

Accordingly, could you guys verify those strings as fast as feasible?

**Comment by el-termikael** [comment]
@DandelionSprout sorry, it must have been a mistake
made you a proofreader — now you can not only translate but also approve strings in AdGuard Websites. please let us know when you do, and we’ll add Norwegian translations to the Reports web form

**Comment by DandelionSprout** [comment]
@el-termikael I think I've got the main strings handled now.

**Comment by el-termikael** [comment]
@DandelionSprout thanks! we'll add your translations soon

**Comment by DandelionSprout** [comment]
Seems to have been implemented by now; thanks.
