### ISSUE TITLE
URL not accepted by reporting tool

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/ReportsWebApp#367]
AdGuard is getting detected on the following website, however can't be reported using the reporting tool due to being rejected for not looking correct.

https://www.sportskeeda.com/esports/mobile-legends-bang-bang-mlbb-tier-list#:~:text=A-tier: Yu Zhong,,Lapu, Jawhead, Aldous, Badaang

![image](https://github.com/user-attachments/assets/de59f1d7-9fe6-452e-abd5-78ac920ec042)

Likely caused by the way Google handles redirected results from Google.com now. Source link: https://www.sportskeeda.com/esports/mobile-legends-bang-bang-mlbb-tier-list#:~:text=A%2Dtier%3A%20Yu%20Zhong%2C,Lapu%2C%20Jawhead%2C%20Aldous%2C%20Badaang

**Comment by Chinaski1** [comment]
Not reproduced

**Comment by emeritaacuity0u** [comment]
@Chinaski1 I can still reproduce this. Use [this](https://www.sportskeeda.com/esports/mobile-legends-bang-bang-mlbb-tier-list#:~:text=A-tier: Yu Zhong,,Lapu, Jawhead, Aldous, Badaang) link.

**Comment by Chinaski1** [comment]
We'll see if there's anything we can do to improve these mechanics
Internal ID: ADG-8898
