### ISSUE TITLE
Can’t upload screenshots from iOS

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/ReportsWebApp#375]
I can’t upload screenshots of sites that I take on iOS using standard system tools almost always, an error message appears. This started about two weeks ago, there were no problems before.

Here is an example screenshot that gives an error when I try to upload it:

<details><summary>Screenshot under spoiler:</summary>

![image](https://github.com/user-attachments/assets/74952200-b9d3-4bc7-8161-2894d8d1f0c6)

</details>

I also wrote to support but did not receive any response to request 964912

**Comment by Chinaski1** [comment]
Hello there!

We have fixed this error, please check again and let us know the result.
