### ISSUE TITLE
Fix the white box on step 6

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#45]
STR:

1) Go to step 6
2) Click on the text field
3) The white box appears for a short period of time

Screenshot:
https://www.screencast.com/t/HRz7uy5GZdM

**Comment by sc0rp10** [comment]
@IldarKamalov can you please help us with debugging this problem?

**Comment by vbagirov** [comment]
It was caused by Grammarly browser extension.
