### ISSUE TITLE
Notify users that they have submitted an invalid screenshot URL

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#58]
If on step 5 an invalid screenshot is submitted, there should be a caption explaining why the user can't proceed.

The text is
>You have entered an invalid screenshot URL!

Position: https://uploads.adguard.com/vbagirovy2cym.png

**Comment by ameshkov** [comment]
@seanl-adg let's use this library for JS alerts:
https://alertifyjs.org/

When invalid image is submitted, we can use "Error Log" message to alert user about it.

**Comment by TPS** [comment]
>_let's use this library for JS alerts:_
_https://alertifyjs.org/_

_Variations of the library source @ https://github.com/alertifyjs_
