### ISSUE TITLE
Github API integration

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#6]
We'll have a special github user to automate reports creation. You should provide an API for searching & creating issues in AdguardFilters repo. It should also have an in-memory cache to make less requests to GitHub.

**Interface:**
```
var githubApi = {
    
    /**
     * Searches for existing issues with the same domain name (or app) and problem type.
     *
     * @returns Array of issues found
     */
    searchIssues(title, labels);
    
    /**
      * Creates a Github issue
      *
      * @returns issue info
      */
    createIssue(title, description, labels);
    
    /**
     * Adds a comment for the specified issue
     * We need it in case if there is an open issue about the very same problem.
     */
    addComment(issueId, commentText);
}
```

**Comment by Bluscream** [comment]
That is a great idea 👍

**Comment by ameshkov** [comment]
Regarding `searchIssues`, we should make an additional step 3.5 in case if there is an existing open issue about the very same problem.

We'll show the list of existing issues so that user didn't need to create a new issue.

**Comment by TPS** [comment]
Given that the bug report _may_ contain sensitive info (especially if reporting when HTTPS Filtering is enabled), this will put your internal report _#_, not the raw _data_ into the GitHub issue, correct?

**Comment by ameshkov** [comment]
@TPS in case of this report webapp, all the information will be entered manually by you. It's just an easy anonymous way to report an issue to github.

Just look at the app mockups in #4

**Comment by Bluscream** [comment]
You should keep that ;D

![](https://puu.sh/vh6XO/26dc1c1772.jpg)
