### ISSUE TITLE
Add new parameters

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#61]
New parameters are:

parameter | explanation
--- | ---
`stealth.strip_url` | Can be `true` or `false`.
`stealth.block_third_party_auth` | Can be `true` or `false`.
`stealth.flash` | Can be `true` or `false`.
`stealth.java` | Can be `true` or `false`.
`custom_filters` | A string that includes URLs (or paths to local files) of custom filters, separated by `%2C`.
`userscripts` | A string that includes URLs (or paths to local files) of installed (and enabled) userscripts, separated by `%2C`.
`user_agent` | Composed similar to `stealth.user_agent`, but contains the real User agent.
`referrer` | A string containing referrer value with which the page was visited.

The web tool also should have these options:

`Strip URLs from tracking parameters`, `Block third-party Authorization requests`, `Block Flash` and `Block Java` should be included as checkboxes in step 4 (with the rest of Stealth Mode options). All of them are optional. Don't forget to reflect this information in the resulting GitHub issue as well.

`referrer`, `custom_filters` and `userscripts` are not selectable anywhere in the web app, they are obtainable only from the user-agent sent by the Windows app. Their contents should be displayed on step 6 inside the editable textarea, like this:

-----

Referrer:
%referrer%

Custom filters: 
%url1%
%url2%
%path1%
%path2%

Custom userscripts:
%url1%
%url2%
%path1%
%path2%

-----

`user_agent` should be parsed to retrieve browser's name and version from it. This information should be used to pre-fill step 3. Selected browser should always be "Other" in this case, and the text area should contain browser name & version, e.g. "Chrome 61.0.3163.100"

**Comment by vbagirov** [comment]
@seanl-adg also please add this info to README.md

**Comment by ameshkov** [comment]
Guys, for both custom filters and userscrips we need to know URLs, not names.

**Comment by ameshkov** [comment]
> custom_filters and userscripts should not be reflected as options anywhere in the web app. This information, however, should be included in the resulting GitHub issue if known. userscripts only exists for Win and Mac, custom_filters exists for Win, Mac and Android.

We should make the information editable somehow. The easiest way would be to put all this information to the textarea on "Filters" step (antiviruses, extensions).

**Comment by vbagirov** [comment]
@ameshkov didn't we decide to remove this textarea and make an emphasis on step 6 instead (by changing and expanding the description there)? We can still have this information included there in cases when we get it from the app.

**Comment by ameshkov** [comment]
As you wish, my point is that it should be visible and editable somewhere

**Comment by TPS** [comment]
> userscripts only exists for Win and Mac

@vbagirov @ameshkov W/ option to re-enable for Android (& I assume iOS) whenever https://github.com/AdguardTeam/AdguardForAndroid/issues/34 lands, correct?

**Comment by vbagirov** [comment]
@TPS in the future, yes, this is only about current state of things.
