### ISSUE TITLE
Mismatch of units for first_party_cookies and third_party_cookies between report app and Adguard for Windows

### ISSUE THREAD

**Issue by confessor-adguard** [AdguardTeam/ReportsWebApp#66]
It will be confusing when user see that "Self-destructing first-party cookies" and "Disable cache for third-party requests" have different values in UI and Report app (mins in UI, seconds in Reports App).
Maybe we need to simply change the protocol description.

**Comment by vbagirov** [comment]
Yes, @seanl-adg please change `stealth.first_party_cookies` and `stealth.third_party_cookies` parameters so that their value is recognized as minutes instead of seconds.
