### ISSUE TITLE
English filter is not added automatically by url query string

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#72]
English filter is not added automatically by url query string (https://reports.adguard.com/de/new_issue.html?filters=2)

![image](https://user-images.githubusercontent.com/10995998/31852424-a9895af6-b677-11e7-8db6-88af446afcf5.png)

edit: Well https://filters.adtidy.org/windows/filters.json says it's 7, but that will add the japanese filter

**Comment by vbagirov** [comment]
@danidoedel I think you confuse `"filterId" :` with `"displayNumber" :`. 

But there seems to be a bug indeed, it doesn't display English filter when you enter 
>https://reports.adguard.com/de/new_issue.html?filters=2

@seanl-adg please have a look at this

**Comment by seanl-adg** [comment]
I suppose this is fixed now @vbagirov could you check it and close the issue?
