### ISSUE TITLE
Separate entries in the resulting GH issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#73]
Current state of things: https://uploads.adguard.com/vbagirovb2igf.png

Each filter should be displayed starting with a new line.

For `Stealth mode` options it will be enough to put a speace after each comma.

**Comment by seanl-adg** [comment]
Fixed in the dev version - https://github.com/vbagirov/test-reports/issues/12#issuecomment-346335607
