### ISSUE TITLE
Overlaping elements (submit page)

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#75]
Processing circle overlaps with other elements:

![5e3423f6-b900-4e32-86d8-b508c4c8fcd9](https://user-images.githubusercontent.com/10995998/31971097-aabaef0c-b91a-11e7-932d-9fd1a29d80d2.png)

Also: Not sure why everything is centered but „Please wait...“ is not...

**Comment by vbagirov** [comment]
@seanl-adg can you have a look please?

**Comment by vbagirov** [comment]
Fixed.
