### ISSUE TITLE
Inconsistent term of „incorrect blocking“

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#77]
Inconsistent term of „incorrect blocking“ at step 2 and 7. I think that should be unified for a better user experience. 

![da618a12-f53e-4bef-a8c8-47a6a64be6b0](https://user-images.githubusercontent.com/10995998/32014463-756ec04a-b9be-11e7-8bbe-7bc0b5016d22.png)

![9b194e46-e711-4524-8f22-7444bd7924d3](https://user-images.githubusercontent.com/10995998/32014473-7c90be6e-b9be-11e7-8345-b9cb80310c3e.png)

**Comment by vbagirov** [comment]
That's on me probably.

**Comment by seanl-adg** [comment]
This was fixed
