### ISSUE TITLE
Script does not detect Chrome browser

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/ReportsWebApp#78]
Script does not detect Chrome browser... selecting "Other" instead:

![image](https://user-images.githubusercontent.com/10995998/32142832-7169fa80-bc9f-11e7-88c8-36693850fe44.png)

(https://reports.adguard.com/de/new_issue.html?product_type=Win&product_version=6.2.433.2167&url=https%3A%2F%2Fgithub.com%2FAdguardTeam%2FReportsWebApp%2Fissues&referrer=https%3A%2F%2Fgithub.com%2FAdguardTeam&user_agent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F62.0.3202.75%20Safari%2F537.36&filters=2.3.4.6.11.12.14&userscripts=https%3A%2F%2FAdguardTeam.github.io%2FAdguardAssistant%2Fassistant.user.js%2Chttps%3A%2F%2FAdguardTeam.github.io%2FPopupBlocker%2Fpopupblocker.user.js&win.wfp=true&stealth.enabled=true&stealth.hide_search_queries=true&stealth.DNT=true&stealth.x_client=true&stealth.disable_third_party_cache=true&stealth.webrtc=true&stealth.push=false&stealth.location=true&stealth.flash=false&stealth.java=false&stealth.strip_url=false&block_third_party_auth=false)

**Comment by vbagirov** [comment]
@danidoedel It does detect Chrome. We only opt to selet 'Other' there so that the full user-agent can be included (it contains the browser's name, too). We will probably come up with a more elegant solution later, but for now this is the way it is.
