### ISSUE TITLE
Implement prioritization of the issues

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#80]
We need prioritization according to site rank and number of visitors and, if it is possible, by source on visit(direct, or from search)

**Comment by ameshkov** [comment]
The only thing we have is Alexa rank.

What exact labels/priority levels should we have?

**Comment by Alex-302** [comment]
I suggest `Issue type` + priorities as in Windows repo: `Critical`, `High`, `Medium`, `Low`
`Critical` - incorrect blocking on extremely popular sites(such as social networks, search, etc);
`High` - missed ads on the sites above and incorrect blocking on the sites with high popularity(for example 100k-1M+ visitors per month);
`Medium` - missed ads
`Low` - missed ads(<50k visitors per month)

**Comment by ameshkov** [comment]
We don't have visitors count, *Alexa rank only*

**Comment by Alex-302** [comment]
damn

**Comment by vbagirov** [comment]
let's make it something like

`Critical` - Alexa rank 1-5000;
`High` - Alexa rank 5k-25k;
`Medium` - Alexa rank 25k-200k;
`Low` - 200k+

Makes more sense if you ask me.

**Comment by Alex-302** [comment]
`NSFW` sites should not have priority, higher than `Medium`, because a lot of reports are NSFW sites, which have high attendance.

**Comment by vbagirov** [comment]
EDIT: for now, let's stick to the initial Alex's distribution:

`Critical` - Alexa rank 1-5k;
`High` - Alexa rank 5k-8k;
`Medium` - Alexa rank 8k-200k;
`Low` - Alexa rank 200k+.

**Comment by ameshkov** [comment]
Works great, but we should also somehow prioritize reports about ads in apps

**Comment by Alex-302** [comment]
I think `Annoyances` and `Social widgets` must have priority not higher than `Medium`.

**Comment by seanl-adg** [comment]
`pull-requests/40`

**Comment by vbagirov** [comment]
@seanl-adg while we are at it, please move the boundaries for the priorities: 

`Critical` - Alexa rank 1-5k;
`High` - Alexa rank 5k-13k (was 5k-8k);
`Medium` - Alexa rank 13k-200k (was 8k-200k);
`Low` - Alexa rank 200k+.

**Comment by seanl-adg** [comment]
@vbagirov just to be sure, is it something that has reached consensus among others or your arbitrary opinion?

**Comment by vbagirov** [comment]
@seanl-adg it was Alex's idea based on his observations. 

BTW we should also implement prioritization for Google Play apps. @sc0rp10 says you have everything that is required for it. I'll update the issue with exact numbers later.

**Comment by vbagirov** [comment]
After discussing with Alex:

`Critical`: >5m installs
`High`: 1m-5m installs
`Medium`: 300k-1m installs
`Low`: <300k installs

**Comment by seanl-adg** [comment]
`pull-requests/57`

**Comment by vbagirov** [comment]
Done.
