### ISSUE TITLE
Hide screenshots under a spoiler in the resulting issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#81]
You should use
```
<details>

![image]()
</details>
```
to display screenshots.

**Comment by danidoedel** [comment]
Consider using this:

```
<details>
<summary>Screenshot(s)</summary>

![image]()

</details>
```

Resulting in:

<details>
<summary>Screenshot(s)</summary>

![image]()

</details>

**Comment by vbagirov** [comment]
@danidoedel yes that's a better option.

@seanl-adg please take into account.

**Comment by seanl-adg** [comment]
`pull-requests/41`

**Comment by vbagirov** [comment]
Done.
