### ISSUE TITLE
User should be able to specify his or her Github account

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ReportsWebApp#83]
If user wants to receive feedback from the newly created issue, he or she should be able to specify the Github account.

We, in turn, should add this account to the issue watchers.

**Comment by ameshkov** [comment]
Here is how it should look like:
https://uploads.adguard.com/up04_z6mnj_mobile.nytimes.com__Issue_7723__AdguardTeamAdguardFilters_.png

**Comment by vbagirov** [comment]
We can (and probably should) add a button/link besides this option to register on GitHub. Something like

```Don't have a GitHub account? Register [now](link)!```

It should open in new tab, obviously.

**Comment by ameshkov** [comment]
Absolutely! 

We should also explain why would he need it:

1. The user might want to learn when the issue is resolved
2. We may need to ask him additional questions in order to resolve the issue

**Comment by seanl-adg** [comment]
`pull-requests/43`

**Comment by vbagirov** [comment]
Works, but needs one minor improvement: currently it is possible to tick the checkbox but leave the text input area empty. There should be validation that requires at least some characters typed in.

**Comment by seanl-adg** [comment]
`pull-requests/58`

**Comment by vbagirov** [comment]
Done.
