### ISSUE TITLE
Ask additional info for Android case

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#87]
Step 1: when user selects 'AdGuard for Android' we should also ask him for Android version, not only AdGuard version. This version should be reflected in the final issue: https://uploads.adguard.com/vbagirovfcbqa.png

Step 3: remove the `If you don't have HTTPS filtering enabled, please enable it. Is the problem still present?` question. Instead, add a question on step 4 about the enabled HTTPS filtering.
https://uploads.adguard.com/vbagirov9y8vs.png

**Comment by seanl-adg** [comment]
`pull-requests/42`

**Comment by vbagirov** [comment]
Done.
