### ISSUE TITLE
Screenshot validation bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#89]
See the attached 'screenshot' here: https://github.com/AdguardTeam/AdguardFilters/issues/7679

**Comment by seanl-adg** [comment]
I'm not sure how the issue reporter entered the url `https://palacesquare.rambler.ru/qnnsefkok/eWR4ZXkubnMxd2FAeyJkYXRhIjp7IkFjdGlvbiI6IlJlZGlyZWN0IiwiUmVmZmVyZXIiOiJodHRwczovL3Jucy5vbmxpbmUvIiwiUHJvdG9jb2wiOiJodHRwczoiLCJIb3N0Ijoicm5zLm9ubGluZSJ9LCJsaW5rIjo/iaHR0cHM6Ly9wYWxhY2VzcXVhcmUucmFtYmxlci5ydS9tbnFzcmdwc2QvTkhoMlpIb3VZbXAwYjI1aU9YUTJjemxyT1VCN0ltUmhkR0VpT25zaVFXTjBhVzl1SWpvaVVtVmthWEpsWTNRaWZTd2liR2x1YXlJNkltaD/BkSEE2THk5aGJpNTVZVzVrWlhndWNuVXZZMjkxYm5Rdk1FSjVURFl0YTJaU1dGTTBNREF3TUZwb2FtOTRaekExV0ZCSVNFVjJTekZqYlRWclIzaFRNa0ZITkhZd1QxbGZlVEZGWlRGbFkyOHR/XRGhGTVdaWldYbENieTFrVnpaVVowUk9ZakZDYUc1NU5rWkdWbmRwY2pGWFkyTlZkV2R2Y1RoR1lqTkViM05TYTNoSE0xSnpjMXBUTURNeVVXVXhabEYxV0RodGMzbG5VWFEyTUdweE1YUm1NR0Y2T1RaMmNFMDBlREptUlRFelptRnhSMlZ2VkZwdmMzTmhaMmxFYWxCUlRESjNNaz9hbmFtPXBYYnkxc1pFOTVhbWwyUzBzeiZiZW9yPVFrbE5Za2RzVUdKS1dETnpaaiZiaW9yd249Qk9ORkZWT1ZKUldXMUhOV0p3JmJ6YmVwPU1YYzNlVnBmU0dKeVdtaDNVMCZjcXhwdGlyd3l2PWRGWVcwd01EQXdNVU14YUd4VyZlbW9icHVzbz1NREJwZEhkWlFVcHBNVkkwTVcmZnFiZ2ZsZz1scFprb3dNRGt3TWtaa2RHMHcmZ25kc2t6aHl2cW?duqpmn=Z5eD1Ra1F0WlZsaGVEQk9lVEZzYzEmaHRuYmNpbHd3aXB1dT1sNVFtOHRhMUZhVEhaSFNYaGYmaXNxYT1PRjl4VUZSUGR5MWtORE50VmwmamNwa21jc&eusikh=HRtPTlmWDE5ZlgxOWZYMTh6ZVVjeCZqb25ocmg9Yms1d1JHbFVNak4yUjNCRmFXJmpzeWp4cT05S2EzRXdkRW94UlhVeGMxOXcmcWR6aGhxd2ltPVJr&hkuyplb=cFVaRlJGYkdadU1Ib3RNVCZyYnJpPU5zTWxjd05EQlBkMWMzWW1GRyZycG9rb2J3aXJvPU9HaDRUME5sZVZBNVF6RmZUayZ0ZWhiaXpuZXpxeXVpPWs&iobdob=xYVhRdFZIa3dNbnBxVEU1MyZ1ZHZ1bT1ZM1JWZFdKT2RHRXhWMHd0UVQmdXFndGRoeW5vZXI9SlhTbGRDZUdSUGVXcFdTVTh3JnZjcXliZnh1bT1Jbj&nuydpt=AlM0QifQ%3D%3D`
In the dev version, when I enter this url, it is not validated. 
A reproduction step that works for the dev version would be needed.

**Comment by vbagirov** [comment]
There's no way to find the original poster now, so let's remove the milestone and leave this task as is until there's a new report with the same issue. Now that we mention the user's GH username it should be easier to reproduce.

**Comment by vbagirov** [comment]
Another example: https://github.com/AdguardTeam/AdguardFilters/issues/8036
`https://github.com/AdguardTeam/AdguardFilters/issues/8036`

**Comment by vbagirov** [comment]
Doesn't seen to happen anymore, closing for now until the issue is proven to come back.
