### ISSUE TITLE
Change the spelling of 'Adguard' in the resulting issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#90]
`Adguard` —> `AdGuard`

**Comment by sc0rp10** [comment]
@vbagirov we should update strings in Onesky first

**Comment by vbagirov** [comment]
@sc those phrases are not on OneSky. I meant these: https://uploads.adguard.com/vbagirov7lbkn.png

**Comment by seanl-adg** [comment]
`pull-requests/41`

**Comment by vbagirov** [comment]
Fixed.
