### ISSUE TITLE
Change issue formatting

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#94]
How it should look: https://github.com/AdguardTeam/AdguardFilters/issues/7723

What exactly has to be changed:

 - `###` headers instead of `***`
 - Quote the comment (`>`)
 - Mention (`@username`) the reporter's username (if it was provided, see issue #83)
 - Display the screenshot properly (see issue #81)

**Comment by seanl-adg** [comment]
`pull-requests/41`
I will do `@username` in a separate issue https://github.com/AdguardTeam/ReportsWebApp/issues/83

**Comment by vbagirov** [comment]
We can use https://github.com/AdguardTeam/AnonymousRedirect to show URL. Something like

`[https://example.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://example.org/)`

This way it will be clickable and still won't cause any trouble in terms of referrer tracking.

**Comment by vbagirov** [comment]
@seanl-adg can you do this please? It should be a small change, but a very helpful one for filter developers.

**Comment by ameshkov** [comment]
@vbagirov isn't it already done?

**Comment by vbagirov** [comment]
@ameshkov yep I see it in the last PR, currently on **dev**.
