### ISSUE TITLE
In some cases, URL form is broken

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/ReportsWebApp#95]
**Steps to reproduce**:

1. Open https://reports.adguard.com/en/new_issue.html
2. Select any values
3. *In the step `3`*, write URL like `git.io`

**Expected** an OK result, but **actual one is** an error. This was caused because `http://` is missing?

**Version** stable, **Browser**: Yandex 17.4.1

Bellow is the screenshot.

<details>

![image](https://user-images.githubusercontent.com/18398761/33136604-b1132c54-cfb6-11e7-91d2-344fe7b1fdb9.png)

</details>

**Comment by vitalkanev** [comment]
Also reproduced with Firefox Quantum 57

**Comment by vbagirov** [comment]
@vitalkanev yes, URL always includes the protocol part. It is well explained here, for example: https://doepud.co.uk/blog/anatomy-of-a-url
