### ISSUE TITLE
Attach platfrom-based labels when creating a new GH issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#97]
Windows: `Windows`
Android: `Android`
Mac: `MacOS Browser`
Extensions: `Browser Extension`
Content Blocker: `Content Blocker`
iOS: `iOS Browser`

**Comment by Alex-302** [comment]
Existing labels can be used:
`Windows`
`Android`
`MacOS App`
`Browser Extension`
`iOS App`
`Content Blocker`

**Comment by ameshkov** [comment]
Does it mean we'll create an issue per platform?

**Comment by ameshkov** [comment]
Or should we attach another label when the same website is reported from another platform?

**Comment by Alex-302** [comment]
no, just attack the label.
But it will be convenient, if the issues will be devided:
- Windows, Android, MacOS App;
- Browser Extension
- iOS App, Content Blocker

**Comment by Alex-302** [comment]
no, just attack the label.
But it will be convenient, if the issues will be devided:
- Windows, Android, MacOS App;
- Browser Extension
- iOS App, Content Blocker
or 
- Windows, Android, MacOS App, Chrome/FF/Opera extension;
- safari ext;
- iOS App, Content Blocker

**Comment by ameshkov** [comment]
So we basically need "platform groups":

* Desktop Apps + Main Android App (Windows, Android, MacOS App)
* Extensions (Chrome/FF/Opera)
* Content Blockers (iOS App, Content Blocker, Safari Extension)

If we have an issue with `Windows` label, and a new issue with `Android` label arrives, it should be appended to the existing one.

However, if the new issue reported with `Chrome` (another platform group), we should create a new issue instead.

**Comment by vbagirov** [comment]
Currently, we don't even have options to report ads in desktop apps. But that shouldn't stop us from introducing the platform groups.

@Alex-302 should I delete the 'individual platform' labels or only create 'platform group' labels in addition to the existing ones?

**Comment by vbagirov** [comment]
Ok, there are now these labels:

 * `Desktop & Android Apps` (applicaple in cases of Android apps, Windows and Mac apps (not implemented yet))
 * `Browser Extensions` (applicable in cases of Chrome/Opera/FF extensions)
 * `Content Blockers` (applicable in cases of Safari extension, Content Blocker, iOS)
 * `Windows` (applicable in case of Windows browser problems)
 * `MacOS Browser` (applicable in case of Mac browser problems)
 * `Android` (applicable in case of Android browser problems)

@seanl-adg please take into account.

**Comment by vbagirov** [comment]
Additionally, we should change the issue type-related labels' text:

 * `T: Incorrect Blocking` - in case of "Broken website/App"
 * `T: Anti-Adblock Script` - in case of "Anti-adblock script"
 * `T: Ads` - in case of "Missed ad"
 * `T: Social Widget` - in case of "Social media element"
 * `T: Annoyance` - in case of "Annoyance"

@seanl-adg please discuss the timing with @Alex-302 before changing the applied labels, so you change it simultaneously in the report app and "Filters" repo.

**Comment by vbagirov** [comment]
Update on the applied labels: everything is listed in this [google doc](https://docs.google.com/spreadsheets/d/10kEpPc661M9_JZ3m-DWvkEZbZ7le8xISBuAMLQU2TfI/edit#gid=0).

`P1-P4`, `T`, `N`, `OS` and `G` labels (and `NSFW` if needed) can be applied independently at the same time. 

We don't have manual OS selection yet, so don't apply these labels for browser extensions.

**Comment by ameshkov** [comment]
I agree with @seanl-adg 

Platform groups is a logical thing, not a new label or somewhat.

**Comment by Alex-302** [comment]
removed that labels from doc

**Comment by seanl-adg** [comment]
Product types and problem type labels in `pull-requests/50`, but there is currently no form to provide OS information separately from product type, also why do we not have `N: AdGuard Browser Extensions` label?

**Comment by Alex-302** [comment]
> also why do we not have N: AdGuard Browser Extensions

I will add it

**Comment by vbagirov** [comment]
There's a mistake: currently priority labels are `P1: Low`, `P2: Medium` etc., should be the other way around: `P1: Critical`, `P2: High` etc.

@seanl-adg

**Comment by seanl-adg** [comment]
`pull-requests/57`

**Comment by vbagirov** [comment]
Done.

**Comment by seanl-adg** [comment]
There is one issue, we are attaching `N: AdGuard Browser Extensions` and we should remove the last `s`

**Comment by seanl-adg** [comment]
`pull-requests/61`

**Comment by vbagirov** [comment]
I thought we kinda decided to roll with it. Anyway, I can see your latest changes implemented, closing this.
