### ISSUE TITLE
Rework the filter selection step

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ReportsWebApp#99]
Current implementation is not convenient for users. We should make some changes:

 * Add checkboxes to the list. 
<details>
<summary>Reference:</summary>

![image](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fwww.jqueryscript.net%2Fimages%2FjQuery-Plugin-For-Seachable-Option-List-with-Checkboxes.jpg)

</details>

 * The list should not fold when user ticks a checkbox. The list folds only when user clicks somewhere outside the box.

 * Filters should not disappear from the list when their respective checkboxes become ticked.

 * Divide the list of filters into sections. Sections should be identical to those in AdGuard for Windows Filter editor: AdGuard filters, EasyList, Other. See the screenshot above for a rough reference.

 * Increase the visible height of the list
<details>
<summary>Screenshot:</summary>

![image](https://uploads.adguard.com/vbagirovks10y.png)

</details>

**Comment by vbagirov** [comment]
A good suggestion by @seanl-adg: instead of checkboxes have the background changed for the selected filters. I think it is a cleaner solution than checkboxes, let's go with it.

The only remark is to make this color very distinguishable from the default white.

**Comment by seanl-adg** [comment]
`pull-requests/55`

**Comment by vbagirov** [comment]
@seanl-adg currently filters disappear from the list when selected. I thought we agreed on highlighting them with another color rather than remove from the list.

Other (minor) notes regarding categories:

 - When you search for a filter by typing its name, the filter is shown without its category. Compare:
https://uploads.adguard.com/vbagirovfga30.png
https://uploads.adguard.com/vbagirovfl89z.png 

I suggest displaying the category name if a filter satisfies the search criteria, even if the category name itself doesn't.

 - "AdGuard filters" category name doesn't show when you first unfold the drop-down menu:
https://uploads.adguard.com/vbagirov38thb.png
It's preferrable to show it.

**Comment by vbagirov** [comment]
Another possible solution: show the selected filters just as they are shown now, but at the top so that the user can see what he has selected during the selection process.

**Comment by vbagirov** [comment]
@IldarKamalov here's what we need to do: move the selected filters above the drop-down menu like shown here:
https://uploads.adguard.com/vbagirovh48s0.png

Here's what it should look like approximately:
https://uploads.adguard.com/vbagirovj6b04.png
